import Preloader from "@/layouts/Preloader";
import CookieConsent from "@/components/CookieConsent";
import "@css/plugins.css";
import "@css/style.css";
import "./globals.css";

export const metadata = {
  title: "Atreya",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CookieConsent />
        <Preloader />
        {children}
      </body>
    </html>
  );
}
